version: '3'
services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: portfolio
    ports:
      - "3000:3000"
    environment:
      - STRAPI_URL=https://admin.ruslan-portfolio.com