FROM node:18.14.0
WORKDIR /opt/
COPY ./package.json ./package-lock.json ./nuxt.config.ts ./tsconfig.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install
COPY ./ .
RUN npm run build
EXPOSE 3000
CMD [ "node", ".output/server/index.mjs"]